# Task 2: Some Bowling Game

Bowling is a sport in which a player throws a bowling ball down a synthetic lane and towards ten pins positioned at the end of the lane. The objective is to score points by knocking down as many pins as possible. The following paragraphs describe the basic rules and scoring for the game:

<span style="font-weight:bold;text-decoration:underline;">A bowling game</span>

One game of bowling consists of ten frames. Each frame consists of two chances for the bowler to knock down ten pins.

<span style="font-weight:bold;text-decoration:underline;">Strikes and spares</span>

Knocking down all ten pins on the first throw of any frame is called a strike, denoted by 'X' on the score sheet. If a bowler takes two throws to knock down all ten pins, it is called a spare.

<span style="font-weight:bold;text-decoration:underline;">Scoring and bonus scoring</span>

Each pin that is knocked down is worth 1 point.

A strike is worth 10 points plus the number of pins hit on the next two throws.

A spare is worth 10 points plus the number of pins hit on the next throw.

The total score for a ten frame game ranges from 0 to 300 points.

<span style="font-weight:bold;text-decoration:underline;">The tenth frame</span>

A bowler who strikes on the tenth frame will be given two extra throws.

A bowler who spares on the tenth frame will be given one extra throw. The number of pins hit on these extra throws will be added to the bowler's score.

<span style="font-weight:bold;text-decoration:underline;">Sample Scores</span>

**Player 1**'s score sheet:
<!-- Player 1 -->
<table style="width:80%">
    <tr>
        <th style="text-align:left;">Frame</th>
        <td style="text-align:center" colspan="2">1</td>
        <td style="text-align:center" colspan="2">2</td>
        <td style="text-align:center" colspan="2">3</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">6</td>
        <td style="text-align:center" colspan="2">7</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="3">10</td>
    </tr>
    <tr>
        <th style="text-align:left;">Pins Hit</th>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">7</td>
        <td style="text-align:center">3</td>
        <td style="text-align:center">7</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">1</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">3</td>
        <td style="text-align:center">6</td>
        <td style="text-align:center">4</td>
        <td style="text-align:center">7</td>
        <td style="text-align:center">3</td>
        <td style="text-align:center">3</td>
    </tr>
    <tr>
        <th style="text-align:left;">Frame Score</th>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">17</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">22</td>
        <td style="text-align:center" colspan="2">15</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">17</td>
        <td style="text-align:center" colspan="3">13</td>
    </tr>
    <tr>
        <th style="text-align:left;">Cummulative Score</th>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">37</td>
        <td style="text-align:center" colspan="2">46</td>
        <td style="text-align:center" colspan="2">66</td>
        <td style="text-align:center" colspan="2">96</td>
        <td style="text-align:center" colspan="2">118</td>
        <td style="text-align:center" colspan="2">133</td>
        <td style="text-align:center" colspan="2">138</td>
        <td style="text-align:center" colspan="2">155</td>
        <td style="text-align:center" colspan="3">168</td>
    </tr>
</table>


**Player 2**'s score sheet:
<!-- Player 2 -->
<table style="width:80%">
    <tr>
        <th style="text-align:left;">Frame</th>
        <td style="text-align:center" colspan="2">1</td>
        <td style="text-align:center" colspan="2">2</td>
        <td style="text-align:center" colspan="2">3</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">6</td>
        <td style="text-align:center" colspan="2">7</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="3">10</td>
    </tr>
    <tr>
        <th style="text-align:left;">Pins Hit</th>
        <td style="text-align:center">0</td>
        <td style="text-align:center">5</td>
        <td style="text-align:center">8</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">5</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">6</td>
        <td style="text-align:center">4</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">5</td>
        <td style="text-align:center">8</td>
        <td style="text-align:center">1</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">1</td>
        <td style="text-align:center">5</td>
        <td style="text-align:center">0</td>
    </tr>
    <tr>
        <th style="text-align:left;">Frame Score</th>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">15</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">10</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="2">15</td>
        <td style="text-align:center" colspan="3">5</td>
    </tr>
    <tr>
        <th style="text-align:left;">Cummulative Score</th>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">13</td>
        <td style="text-align:center" colspan="2">28</td>
        <td style="text-align:center" colspan="2">33</td>
        <td style="text-align:center" colspan="2">53</td>
        <td style="text-align:center" colspan="2">63</td>
        <td style="text-align:center" colspan="2">68</td>
        <td style="text-align:center" colspan="2">77</td>
        <td style="text-align:center" colspan="2">92</td>
        <td style="text-align:center" colspan="3">97</td>
    </tr>
</table>

**Player 3**'s score sheet:
<!-- Player 3 -->
<table style="width:80%">
    <tr>
        <th style="text-align:left;">Frame</th>
        <td style="text-align:center" colspan="2">1</td>
        <td style="text-align:center" colspan="2">2</td>
        <td style="text-align:center" colspan="2">3</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">6</td>
        <td style="text-align:center" colspan="2">7</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="3">10</td>
    </tr>
    <tr>
        <th style="text-align:left;">Pins Hit</th>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">1</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">8</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">X</td>
        <td style="text-align:center">X</td>
        <td style="text-align:center">X</td>
    </tr>
    <tr>
        <th style="text-align:left;">Frame Score</th>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">29</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">10</td>
        <td style="text-align:center" colspan="2">0</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="3">30</td>
    </tr>
    <tr>
        <th style="text-align:left;">Cummulative Score</th>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">60</td>
        <td style="text-align:center" colspan="2">89</td>
        <td style="text-align:center" colspan="2">109</td>
        <td style="text-align:center" colspan="2">129</td>
        <td style="text-align:center" colspan="2">139</td>
        <td style="text-align:center" colspan="2">139</td>
        <td style="text-align:center" colspan="2">143</td>
        <td style="text-align:center" colspan="2">163</td>
        <td style="text-align:center" colspan="3">193</td>
    </tr>
</table>

<br>

An algorithm below describes the calculation of bowling scores.

The input, `throws`, is a string containing the sequence of pins knocked down in each throw, a strike is indicated as an 'X'. For example, according to Player 1's score sheet shown above, the value for `throws` will be:

`"X737291XXXX2364733"`.

<pre style='font-family: Courier New, monospace;'>

FUNCTION throw2score(throw: STRING) RETURNS INTEGER
    IF throw = "X" THEN
        RETURN 10
    ELSE:
        RETURN INTEGER(throw)  // Convert to integer
    ENDIF
ENDFUNCTION

FUNCTION calc_score(throws: STRING) RETURNS INTEGER
    // Assume that the input is valid

    DECLARE total_score: INTEGER
    Initialise total_score
    FOR frame = 1 TO 10 DO
        DECLARE frame_score: INTEGER
        IF throws[1] = "X" THEN  // index of throws starts at 1
            frame_score ← 10 + Sum of scores for throws[2] and throws[3]
            Remove the first element from throws
        ELSE
            frame_score ← Sum of scores for throws[1] and throws[2]
            IF frame_score = 10 THEN
                frame_score ← frame_score + score throws[3]
            END IF
            Remove the first two elements from throws
        ENDIF
        total_score ← total_score + frame_score
    ENDFOR
    RETURN total_score
ENDFUNCTION

</pre>

For each of the sub-tasks, add a comment statement at the beginning of the code using the has symbol '#', to indicate the sub-task the program code belongs to, for example:
<table style='border: 1px solid transparent; border-collapse: collapse; width: 80%;margin-left=0'>
<tr>
<td style='border: 1px solid transparent; vertical-align: top; text-align: right; font-family: Courier New, monospace; width: 20%;'>
In [1]:
</td>
<td style='border: 1px solid transparent;'>
<table style='width: 100%;'>
<tr>
<td  style='background-color: #f2f2f2;'>
<pre style='margin: 0; padding: 10px; font-family:Courier New, monospace;'>
# Task 1.1
Program code</pre>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style='border: 1px solid transparent;'></td>
<td style='border: 1px solid transparent;font-family:Courier New,monospace'> Output:</td>
</tr>
</table>

## Task 2.1
Write Python code to implement an algorithm for calculating bowling scores.
<div style='text-align: right; font-family: Courier New, monospace;'>[5]</div>

In [ ]:
# Task 2.1

## Task 2.2
Modify the code implemented in Task 2.1 to include code for writing the score sheet for a player into a file named `SCORE_<player_name>.TXT`, where `<player_name>` is the name of the player. The contents of the file should show the number of pins hit in each frame, the score for that frame and the cumulative score computation. The format of the output should look like this (Player 1 is the name of the player):

<pre style='font-family: Roboto Mono;'>
Player 1 Scoresheet
Frame               1     2      3      4      5     6     7     8      9      10
Pins hit          [ X ][7|3][7|2][9|1][ X ][ X ][ X ][2|3][6|4][7|3|3]
FrameScore    20    17    9    20     30   22   15     5   17    13
Cum. Score    20    37  46    66     96   118  133 138 155  168
</pre>

The code for Task 2.2 should have a different function name from Task 2.1.

<div style='text-align: right; font-family: Courier New, monospace;'>[10]</div>

In [ ]:
# Task 2.2

## Task 2.3
Write Python code to test the code implemented in Task 2.2 by using three test cases for Player 1, Player 2 and Player 3 score sheets as show above. You should generate 3 output files.
<div style='text-align: right; font-family: Courier New, monospace;'>[3]</div>

In [ ]:
# Task 2.3

## Task 2.4

Write Python code to implement a recursive function, `validate(throws)` that will return `True` if the value of throws is valid and `False`, if invalid. The value of throws is described above.

The value of throws is valid if it contains a sequence of values that allows a score to be computed for a ten frame bowling game.

For example in the following games played:

<table style="width:80%">
    <tr>
        <th style="text-align:left;">Frame</th>
        <td style="text-align:center" colspan="2">1</td>
        <td style="text-align:center" colspan="2">2</td>
        <td style="text-align:center" colspan="2">3</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">6</td>
        <td style="text-align:center" colspan="2">7</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="3">10</td>
    </tr>
    <tr>
        <th style="text-align:left;">Pins Hit</th>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">1</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">8</td>
        <td style="text-align:center">2</td>
        <td style="text-align:center">X</td>
        <td style="text-align:center">X</td>
        <td style="text-align:center">X</td>
    </tr>
    <tr>
        <th style="text-align:left;">Frame Score</th>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">29</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="2">10</td>
        <td style="text-align:center" colspan="2">0</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">20</td>
        <td style="text-align:center" colspan="3">30</td>
    </tr>
    <tr>
        <th style="text-align:left;">Cummulative Score</th>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">60</td>
        <td style="text-align:center" colspan="2">89</td>
        <td style="text-align:center" colspan="2">109</td>
        <td style="text-align:center" colspan="2">129</td>
        <td style="text-align:center" colspan="2">139</td>
        <td style="text-align:center" colspan="2">139</td>
        <td style="text-align:center" colspan="2">143</td>
        <td style="text-align:center" colspan="2">163</td>
        <td style="text-align:center" colspan="3">193</td>
    </tr>
</table>

- `validate("XXXX91X00228291X")` should return `True`.
- `validate("XXXX91X00228290")` should return `True`.
- `validate("XXXX91X00228291")` should return `False`, as the tenth frame is a spare, there should be 1 more value.
- `validate("XXXX91")` should return `False`, as there are not enough values to compute a score for ten frames.

<table style="width:80%">
    <tr>
        <th style="text-align:left;">Frame</th>
        <td style="text-align:center" colspan="2">1</td>
        <td style="text-align:center" colspan="2">2</td>
        <td style="text-align:center" colspan="2">3</td>
        <td style="text-align:center" colspan="2">4</td>
        <td style="text-align:center" colspan="2">5</td>
        <td style="text-align:center" colspan="2">6</td>
        <td style="text-align:center" colspan="2">7</td>
        <td style="text-align:center" colspan="2">8</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="3">10</td>
    </tr>
    <tr>
        <th style="text-align:left;">Pins Hit</th>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center">9</td>
        <td style="text-align:center">0</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" colspan="2">X</td>
        <td style="text-align:center" >X</td>
        <td style="text-align:center">8</td>
        <td style="text-align:center">0</td>
    </tr>
    <tr>
        <th style="text-align:left;">Frame Score</th>
        <td style="text-align:center" colspan="2">29</td>
        <td style="text-align:center" colspan="2">19</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">29</td>
        <td style="text-align:center" colspan="2">19</td>
        <td style="text-align:center" colspan="2">9</td>
        <td style="text-align:center" colspan="2">30</td>
        <td style="text-align:center" colspan="2">28</td>
        <td style="text-align:center" colspan="3">18</td>
    </tr>
    <tr>
        <th style="text-align:left;">Cummulative Score</th>
        <td style="text-align:center" colspan="2">29</td>
        <td style="text-align:center" colspan="2">48</td>
        <td style="text-align:center" colspan="2">57</td>
        <td style="text-align:center" colspan="2">87</td>
        <td style="text-align:center" colspan="2">116</td>
        <td style="text-align:center" colspan="2">135</td>
        <td style="text-align:center" colspan="2">144</td>
        <td style="text-align:center" colspan="2">174</td>
        <td style="text-align:center" colspan="2">202</td>
        <td style="text-align:center" colspan="3">220</td>
    </tr>
</table>

- `validate("XX90XXX90XX8080")` should return `True`.
- `validate("XX90XXX90XX")` should return `False`, as the tenth frame is a strike, there should be two more values.
- `validate("XX9XXX90XX8080")` should return `False`, as the values for the third frame is incorrect.
- `validate("XX95XXX90XX8080")` should return `False`, as the values for the third frame is incorrect.
- `validate("XX90XXX90XX808z")` should return `False`, as "z" is an invalid value [9]

In [ ]:
# Task 2.4

## Task 2.5
Write Python code to test the `validate` function in Task 2.4, using one valid, one boundary and one invalid test case. 
<div style='text-align: right; font-family: Courier New, monospace;'>[3]</div>

In [ ]:
# Task 2.5